/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Domain.InvoiceRegistry;
import Domain.Invoices;
import Domain.SalesRtn;
import Domain.SalesRtnRegistry;
import Domain.Stocks;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Shiyanrox
 */
public class CustomerRTN extends javax.swing.JFrame {

    /**
     * Creates new form CustomerRTN
     */
    public CustomerRTN() {
        initComponents();
        setID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtRTNNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dcRTNDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txtInvoNo = new javax.swing.JTextField();
        btnLoad = new javax.swing.JButton();
        lblCustomer = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblPID = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtQTY = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        lblBatch = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductselect = new javax.swing.JTable();
        lblPrice = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVrndorRTN = new javax.swing.JTable();
        btnRmvItem = new javax.swing.JButton();
        btnRmvAll = new javax.swing.JButton();
        btnGenerate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtNet = new javax.swing.JTextField();
        txtDiscuntPresentage = new javax.swing.JTextField();
        txtDiscountValue = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DistributerX: Sales Return");

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("RTN Note No:");

        txtRTNNo.setEditable(false);

        jLabel1.setText("Date");

        jLabel2.setText("Invoice No");

        txtInvoNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInvoNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInvoNoKeyTyped(evt);
            }
        });

        btnLoad.setText("Load");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRTNNo, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(txtInvoNo))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dcRTNDate, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnLoad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dcRTNDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtRTNNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtInvoNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLoad)))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel9.setText("QTY");

        txtQTY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQTYKeyTyped(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/FontAwesome_f067(1)_24.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tblProductselect.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "P Code", "Batch", "Description", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductselect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblProductselectMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductselect);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtQTY, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdd))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblPID, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblPID, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtQTY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblVrndorRTN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Product Code", "Batch", "Description", "Selling Price", "QTY", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblVrndorRTN);
        if (tblVrndorRTN.getColumnModel().getColumnCount() > 0) {
            tblVrndorRTN.getColumnModel().getColumn(0).setMaxWidth(40);
            tblVrndorRTN.getColumnModel().getColumn(1).setMaxWidth(50);
            tblVrndorRTN.getColumnModel().getColumn(5).setMaxWidth(50);
        }

        btnRmvItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/FontAwesome_f068(0)_24.png"))); // NOI18N
        btnRmvItem.setText("Remove Item");
        btnRmvItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRmvItemActionPerformed(evt);
            }
        });

        btnRmvAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/FontAwesome_f00d(0)_24.png"))); // NOI18N
        btnRmvAll.setText("Remove All");
        btnRmvAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRmvAllActionPerformed(evt);
            }
        });

        btnGenerate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/FontAwesome_f085(1)_24.png"))); // NOI18N
        btnGenerate.setText("Generate");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/FontAwesome_f05c(0)_24.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Total");

        txtTotal.setEditable(false);

        txtNet.setEditable(false);

        txtDiscuntPresentage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiscuntPresentageKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiscuntPresentageKeyTyped(evt);
            }
        });

        txtDiscountValue.setEditable(false);

        jLabel10.setText("Net Total");

        jLabel11.setText("Discount%");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnRmvItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRmvAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(btnGenerate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(txtDiscuntPresentage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNet, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiscountValue, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtTotal))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDiscountValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiscuntPresentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRmvItem)
                    .addComponent(btnRmvAll)
                    .addComponent(btnCancel)
                    .addComponent(btnGenerate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        Invoices invo = new Invoices();
        Invoices invoObj = invo.viewAInvoices(Integer.parseInt(txtInvoNo.getText()));
        lblCustomer.setText(invoObj.getCustomer());
        this.loadProductTable(Integer.parseInt(txtInvoNo.getText()));
    }//GEN-LAST:event_btnLoadActionPerformed

    private void tblProductselectMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductselectMouseReleased
        String item = tblProductselect.getModel().getValueAt(tblProductselect.getSelectedRow(), 0).toString();
        String Batch = tblProductselect.getModel().getValueAt(tblProductselect.getSelectedRow(), 1).toString();
        String itemV = tblProductselect.getModel().getValueAt(tblProductselect.getSelectedRow(), 2).toString();
        String Price = tblProductselect.getModel().getValueAt(tblProductselect.getSelectedRow(), 3).toString();
        lblPID.setText(item);
        lblDescription.setText(itemV);
        lblBatch.setText(Batch);
        lblPrice.setText(Price);
    }//GEN-LAST:event_tblProductselectMouseReleased

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        int count = tblVrndorRTN.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel) tblVrndorRTN.getModel();
        boolean check = false;
        int raw = 0;
        int tbRaw = 0;
        while (count > raw) {
            if (Integer.parseInt(dtm.getValueAt(raw, 1).toString()) == Integer.parseInt(lblPID.getText())) {
                check = true;
                tbRaw = raw;

            }
            raw++;
        }
        if (check) {
            int currentQty = Integer.parseInt(dtm.getValueAt(tbRaw, 5).toString());
            int newQty = currentQty + Integer.parseInt(txtQTY.getText());
            dtm.setValueAt(newQty, tbRaw, 5);
            dtm.setValueAt(newQty * Float.parseFloat(lblPrice.getText()), tbRaw, 6);
        } else {

            count++;

            Vector v = new Vector();
            v.add(count);
            v.add(lblPID.getText());
            v.add(lblBatch.getText());
            v.add(lblDescription.getText());
            v.add(lblPrice.getText());
            v.add(txtQTY.getText());
            v.add(Integer.parseInt(txtQTY.getText()) * Float.parseFloat(lblPrice.getText()));
            dtm.addRow(v);
        }
        lblPID.setText("");
        lblDescription.setText("");
        txtQTY.setText("");
        lblBatch.setText("");
        lblPrice.setText("");

        float total = this.calNet(tblVrndorRTN, 6);
        txtNet.setText(total + "");
        setDiscTotal(total, Float.parseFloat(txtDiscuntPresentage.getText()));
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtDiscuntPresentageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscuntPresentageKeyReleased
        setDiscTotal(Float.parseFloat(txtNet.getText()), Float.parseFloat(txtDiscuntPresentage.getText()));
    }//GEN-LAST:event_txtDiscuntPresentageKeyReleased

    private void btnRmvItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRmvItemActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tblVrndorRTN.getModel();
        if (dtm.getRowCount() > 0) {
            try {
                dtm.removeRow(tblVrndorRTN.getSelectedRow());
                float net = this.calNet(tblVrndorRTN, 6);
                txtNet.setText(net + "");
                setDiscTotal(net, Float.parseFloat(txtDiscuntPresentage.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Please Select a Raw !", "Oops", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No Data Available !", "Oops", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRmvItemActionPerformed

    private void btnRmvAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRmvAllActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tblVrndorRTN.getModel();
        dtm.setRowCount(0);
        float net = this.calNet(tblVrndorRTN, 6);
        txtNet.setText(net + "");
        setDiscTotal(net, Float.parseFloat(txtDiscuntPresentage.getText()));

    }//GEN-LAST:event_btnRmvAllActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        if (dcRTNDate.getDate() == null) {
            JOptionPane.showMessageDialog(rootPane, "Please Select a Date", "Data Missing", JOptionPane.ERROR_MESSAGE);
        } else {
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String dt = df.format(dcRTNDate.getDate());

            boolean stat = this.addSalesRtn(Integer.parseInt(txtRTNNo.getText()), Integer.parseInt(txtInvoNo.getText()), lblCustomer.getText(), dt, Float.parseFloat(txtNet.getText()), Float.parseFloat(txtDiscountValue.getText()), Float.parseFloat(txtTotal.getText()));
            if (stat) {
                JOptionPane.showMessageDialog(rootPane, "Return Note Added Successfully", "Oparation Complete", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error in Return Note Adding", "Oparation Incomplete", JOptionPane.ERROR_MESSAGE);
            }
this.printReport();
            this.clearAll();
        }
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void txtInvoNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInvoNoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInvoNoKeyReleased

    private void txtInvoNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInvoNoKeyTyped
        char c = evt.getKeyChar();
        if (!(c <= '9' && c >= '0')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtInvoNoKeyTyped

    private void txtQTYKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQTYKeyTyped
        char c = evt.getKeyChar();
        if (!(c <= '9' && c >= '0')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtQTYKeyTyped

    private void txtDiscuntPresentageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscuntPresentageKeyTyped
        char c = evt.getKeyChar();
        if (!(c <= '9' && c >= '0' || c == '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDiscuntPresentageKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerRTN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerRTN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerRTN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerRTN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerRTN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnRmvAll;
    private javax.swing.JButton btnRmvItem;
    private com.toedter.calendar.JDateChooser dcRTNDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBatch;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblPID;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JTable tblProductselect;
    private javax.swing.JTable tblVrndorRTN;
    private javax.swing.JTextField txtDiscountValue;
    private javax.swing.JTextField txtDiscuntPresentage;
    private javax.swing.JTextField txtInvoNo;
    private javax.swing.JTextField txtNet;
    private javax.swing.JTextField txtQTY;
    private javax.swing.JTextField txtRTNNo;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void setID() {

        int id;
        SalesRtn obj = new SalesRtn();
        id = obj.getLastRTNID();
        id++;
        txtRTNNo.setText(id + "");
        Date date = new Date();
        dcRTNDate.setDate(date);
        txtDiscuntPresentage.setText("0");

    }

    private void loadProductTable(int invoId) {
        InvoiceRegistry Productsobj = new InvoiceRegistry();
        ArrayList<InvoiceRegistry> ProductsList = Productsobj.loadInvoiceRegistrybyInvono(invoId);
        if (ProductsList.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Sorry ! No Product Found.");
        } else {
            DefaultTableModel dtm = (DefaultTableModel) tblProductselect.getModel();
            dtm.setRowCount(0);
            int count = 0;
            while (ProductsList.size() > count) {
                Vector v = new Vector();
                InvoiceRegistry Productss = new InvoiceRegistry();
                Productss = ProductsList.get(count);

                v.add(Productss.getPID());
                v.add(Productss.getBatch());
                v.add(Productss.getDescription());
                v.add(Productss.getSPrice());

                dtm.addRow(v);
                count++;

            }
        }

    }

    private float calNet(JTable tbl, int col) {
        float total = 0;
        DefaultTableModel dtm = (DefaultTableModel) tbl.getModel();
        for (int i = 0; tbl.getRowCount() > i; i++) {
            total += Float.parseFloat(dtm.getValueAt(i, col).toString());
        }
        return total;
    }

    private void setDiscTotal(float net, float rate) {
        float disc = (net / 100) * rate;
        float total = net - disc;
        txtDiscountValue.setText(disc + "");
        txtTotal.setText(total + "");
    }

    private boolean addSalesRtn(int id, int invoNo, String Customer, String date, float Net, float Discount, float total) {
        boolean status;
        SalesRtn obj = new SalesRtn();
        obj.setRtnNoteNo(id);
        obj.setInvoiceNo(invoNo);
        obj.setCustomer(Customer);
        obj.setDate(date);
        obj.setNet(Net);
        obj.setDiscount(Discount);
        obj.setTotal(total);

        status = obj.addSalesRtn(obj);
        if (status) {
            status = addInvoicesregistryBulk(obj);
        }

        return status;
    }

    private boolean addInvoicesregistryBulk(SalesRtn obj) {
        ArrayList<SalesRtnRegistry> list = new ArrayList<SalesRtnRegistry>();
        DefaultTableModel dtm = (DefaultTableModel) tblVrndorRTN.getModel();

        for (int raw_id = 0; tblVrndorRTN.getRowCount() > raw_id; raw_id++) {
            SalesRtnRegistry regObj = new SalesRtnRegistry();
            regObj.setRtnNoteNo(obj.getRtnNoteNo());
            regObj.setPID(Integer.parseInt(dtm.getValueAt(raw_id, 1).toString()));
            regObj.setBatch(dtm.getValueAt(raw_id, 2).toString());
            regObj.setDescription(dtm.getValueAt(raw_id, 3).toString());
            regObj.setSPrice(Float.parseFloat(dtm.getValueAt(raw_id, 4).toString()));
            regObj.setQty(Integer.parseInt(dtm.getValueAt(raw_id, 5).toString()));
            regObj.setAmount(Float.parseFloat(dtm.getValueAt(raw_id, 6).toString()));

            list.add(regObj);
        }
        SalesRtnRegistry PRobj = new SalesRtnRegistry();
        boolean stat = PRobj.addSalesRtnRegistryBulk(list);
        if (stat) {
            stat = updateStockQty(list);
        }
        return stat;
    }

    private void clearAll() {
        DefaultTableModel dtm = (DefaultTableModel) tblVrndorRTN.getModel();
        dtm.setRowCount(0);

        setID();
    }

    public boolean updateStockQty(ArrayList<SalesRtnRegistry> list) {
        Stocks obj = new Stocks();
        boolean stat = false;
        for (int count = 0; list.size() > count; count++) {
            //this is SalesRtn so the type is 1
            SalesRtnRegistry Invoobj = list.get(count);
            stat = obj.updateQty(Invoobj.getPID(), Invoobj.getBatch(), Invoobj.getQty(), 1);
        }
        return stat;
    }
    private void printReport() {
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String dt = df.format(dcRTNDate.getDate());
        try {
            JRTableModelDataSource ds = new JRTableModelDataSource(tblVrndorRTN.getModel());
            String rs = "src\\RPT\\SalesRTN.jrxml";
            Map<String, Object> param = new HashMap<String, Object>();
            param.put("InNo", txtRTNNo.getText());
            param.put("C_name", lblCustomer.getText());
            param.put("pono", txtInvoNo.getText());
            param.put("In_date", dt);
            param.put("Net", txtNet.getText());
            param.put("Total", txtTotal.getText());
            param.put("DiscRate", txtDiscuntPresentage.getText());
            param.put("DiscAmount", txtDiscountValue.getText());

            JasperReport jr = JasperCompileManager.compileReport(rs);
            JasperPrint jp = JasperFillManager.fillReport(jr, param, ds);
            JasperViewer.viewReport(jp, false);

        } catch (JRException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
}
