/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Domain.Customer;
import Domain.InvoiceRegistry;
import Domain.Invoices;
import Domain.Products;
import Domain.Stocks;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Shiyanrox
 */
public class Invoice extends javax.swing.JFrame {

    /**
     * Creates new form Invoice
     */
    public Invoice() {
        initComponents();
        loadComboCustomer();
        setID();
        loadProductTable();
        txtCreditPeriod.setText(0 + "");
        txtDiscuntPresentage.setText(0 + "");
        jPanel5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtInvoiceNo = new javax.swing.JTextField();
        ddlCustomer = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ddlPaymentType = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtCreditPeriod = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPOno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dcInvoice = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblproductSelect = new javax.swing.JTable();
        lblPID = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtQTY = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtProductFind = new javax.swing.JTextField();
        lblBatch = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInvoice = new javax.swing.JTable();
        btnRmvItem = new javax.swing.JButton();
        btnRmvAll = new javax.swing.JButton();
        btnGenerate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNet = new javax.swing.JTextField();
        txtDiscountValue = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtDiscuntPresentage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DistributerX: Invoice");

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Invoice No");

        jLabel8.setText("Customer");

        txtInvoiceNo.setEditable(false);

        ddlCustomer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Invoice Date");

        jLabel1.setText("Invoice Type ");

        ddlPaymentType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Credit" }));
        ddlPaymentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddlPaymentTypeActionPerformed(evt);
            }
        });

        jLabel5.setText("Credit Period");

        txtCreditPeriod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCreditPeriodKeyTyped(evt);
            }
        });

        jLabel6.setText("days.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCreditPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCreditPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("PO No");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(ddlCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(dcInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ddlPaymentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPOno, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(txtInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ddlCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(dcInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ddlPaymentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPOno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblproductSelect.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "P Code", "Batch", "Description", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblproductSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblproductSelectMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblproductSelect);
        if (tblproductSelect.getColumnModel().getColumnCount() > 0) {
            tblproductSelect.getColumnModel().getColumn(0).setMaxWidth(40);
            tblproductSelect.getColumnModel().getColumn(1).setMaxWidth(60);
        }

        jLabel9.setText("QTY");

        txtQTY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQTYKeyTyped(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/FontAwesome_f067(1)_24.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel13.setText("Search");

        txtProductFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProductFindKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtQTY, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAdd)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(lblPID, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtProductFind))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtProductFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtQTY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Product Code", "Batch", "Description", "UnitPrice", "QTY", "Amount"
            }
        ));
        jScrollPane2.setViewportView(tblInvoice);
        if (tblInvoice.getColumnModel().getColumnCount() > 0) {
            tblInvoice.getColumnModel().getColumn(0).setMaxWidth(35);
            tblInvoice.getColumnModel().getColumn(1).setMaxWidth(50);
            tblInvoice.getColumnModel().getColumn(2).setMaxWidth(60);
            tblInvoice.getColumnModel().getColumn(5).setMaxWidth(50);
        }

        btnRmvItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/FontAwesome_f068(0)_24.png"))); // NOI18N
        btnRmvItem.setText("Remove Item");
        btnRmvItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRmvItemActionPerformed(evt);
            }
        });

        btnRmvAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/FontAwesome_f00d(0)_24.png"))); // NOI18N
        btnRmvAll.setText("Remove All");
        btnRmvAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRmvAllActionPerformed(evt);
            }
        });

        btnGenerate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/FontAwesome_f085(1)_24.png"))); // NOI18N
        btnGenerate.setText("Generate");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/FontAwesome_f05c(0)_24.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel10.setText("Net Total");

        jLabel11.setText("Discount%");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Total");

        txtNet.setEditable(false);

        txtDiscountValue.setEditable(false);

        txtTotal.setEditable(false);

        txtDiscuntPresentage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiscuntPresentageKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiscuntPresentageKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnRmvItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRmvAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiscuntPresentage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDiscountValue)
                            .addComponent(txtNet)
                            .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGenerate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRmvItem)
                        .addComponent(btnRmvAll))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtNet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtDiscountValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiscuntPresentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnGenerate))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtProductFindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProductFindKeyReleased
        this.loadSerchProductTable(txtProductFind.getText());
    }//GEN-LAST:event_txtProductFindKeyReleased

    private void tblproductSelectMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblproductSelectMouseReleased
        String item = tblproductSelect.getModel().getValueAt(tblproductSelect.getSelectedRow(), 0).toString();
        String Batch = tblproductSelect.getModel().getValueAt(tblproductSelect.getSelectedRow(), 1).toString();
        String itemV = tblproductSelect.getModel().getValueAt(tblproductSelect.getSelectedRow(), 2).toString();
        String Price = tblproductSelect.getModel().getValueAt(tblproductSelect.getSelectedRow(), 3).toString();
        lblPID.setText(item);
        lblDescription.setText(itemV);
        lblBatch.setText(Batch);
        lblPrice.setText(Price);
    }//GEN-LAST:event_tblproductSelectMouseReleased

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (txtQTY.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, " Qty Cannot be Empty!", "Data Missing", JOptionPane.ERROR_MESSAGE);
        } else {
            int count = tblInvoice.getRowCount();
            DefaultTableModel dtm = (DefaultTableModel) tblInvoice.getModel();
            boolean check = false;
            int raw = 0;
            int tbRaw = 0;
            while (count > raw) {
                if (Integer.parseInt(dtm.getValueAt(raw, 1).toString()) == Integer.parseInt(lblPID.getText())) {
                    check = true;
                    tbRaw = raw;

                }
                raw++;
            }
            if (check) {
                int currentQty = Integer.parseInt(dtm.getValueAt(tbRaw, 5).toString());
                int newQty = currentQty + Integer.parseInt(txtQTY.getText());
                dtm.setValueAt(newQty, tbRaw, 5);
                dtm.setValueAt(newQty * Float.parseFloat(lblPrice.getText()), tbRaw, 6);
            } else {

                count++;

                Vector v = new Vector();
                v.add(count);
                v.add(lblPID.getText());
                v.add(lblBatch.getText());
                v.add(lblDescription.getText());
                v.add(lblPrice.getText());
                v.add(txtQTY.getText());
                v.add(Integer.parseInt(txtQTY.getText()) * Float.parseFloat(lblPrice.getText()));
                dtm.addRow(v);
            }
            lblPID.setText("");
            lblDescription.setText("");
            txtQTY.setText("");
            lblBatch.setText("");
            lblPrice.setText("");

            float total = this.calNet(tblInvoice, 6);
            txtNet.setText(total + "");
            setDiscTotal(total, Float.parseFloat(txtDiscuntPresentage.getText()));
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRmvItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRmvItemActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tblInvoice.getModel();
        if (dtm.getRowCount() > 0) {
            try {
                dtm.removeRow(tblInvoice.getSelectedRow());
                float net = this.calNet(tblInvoice, 6);
                txtNet.setText(net + "");
                setDiscTotal(net, Float.parseFloat(txtDiscuntPresentage.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Please Select a Raw !", "Oops", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No Data Available !", "Oops", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRmvItemActionPerformed

    private void btnRmvAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRmvAllActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tblInvoice.getModel();
        dtm.setRowCount(0);
        float net = this.calNet(tblInvoice, 6);
        txtNet.setText(net + "");
        setDiscTotal(net, Float.parseFloat(txtDiscuntPresentage.getText()));
    }//GEN-LAST:event_btnRmvAllActionPerformed

    private void txtDiscuntPresentageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscuntPresentageKeyReleased
        setDiscTotal(Float.parseFloat(txtNet.getText()), Float.parseFloat(txtDiscuntPresentage.getText()));
    }//GEN-LAST:event_txtDiscuntPresentageKeyReleased

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        if (dcInvoice.getDate() == null) {
            JOptionPane.showMessageDialog(rootPane, "Please Select a Date", "Data Missing", JOptionPane.ERROR_MESSAGE);
        } else {
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String dt = df.format(dcInvoice.getDate());

            boolean stat = this.addInvoices(Integer.parseInt(txtInvoiceNo.getText()), ddlPaymentType.getSelectedItem().toString(), txtPOno.getText(), Integer.parseInt(txtCreditPeriod.getText()), dt, ddlCustomer.getSelectedItem().toString(), Float.parseFloat(txtNet.getText()), Float.parseFloat(txtDiscountValue.getText()), Float.parseFloat(txtTotal.getText()), 1);
            if (stat) {
                JOptionPane.showMessageDialog(rootPane, "Invoice Added Successfully", "Oparation Complete", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error in Invoice Adding", "Oparation Incomplete", JOptionPane.ERROR);
            }
            this.printReport();

            this.clearAll();
        }
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtCreditPeriodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCreditPeriodKeyTyped
        char c = evt.getKeyChar();
        if (!(c <= '9' && c >= '0')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCreditPeriodKeyTyped

    private void ddlPaymentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddlPaymentTypeActionPerformed
        if (ddlPaymentType.getSelectedIndex() == 0) {
            jPanel5.setVisible(false);
        } else {
            jPanel5.setVisible(true);
        }
    }//GEN-LAST:event_ddlPaymentTypeActionPerformed

    private void txtQTYKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQTYKeyTyped
        char c = evt.getKeyChar();
        if (!(c <= '9' && c >= '0')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtQTYKeyTyped

    private void txtDiscuntPresentageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscuntPresentageKeyTyped
        char c = evt.getKeyChar();
        if (!(c <= '9' && c >= '0' || c == '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDiscuntPresentageKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnRmvAll;
    private javax.swing.JButton btnRmvItem;
    private com.toedter.calendar.JDateChooser dcInvoice;
    private javax.swing.JComboBox ddlCustomer;
    private javax.swing.JComboBox ddlPaymentType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBatch;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblPID;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JTable tblInvoice;
    private javax.swing.JTable tblproductSelect;
    private javax.swing.JTextField txtCreditPeriod;
    private javax.swing.JTextField txtDiscountValue;
    private javax.swing.JTextField txtDiscuntPresentage;
    private javax.swing.JTextField txtInvoiceNo;
    private javax.swing.JTextField txtNet;
    private javax.swing.JTextField txtPOno;
    private javax.swing.JTextField txtProductFind;
    private javax.swing.JTextField txtQTY;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
private void setID() {

        int id;
        Invoices obj = new Invoices();
        id = obj.getLastGRNID();
        id++;
        txtInvoiceNo.setText(id + "");
        Date date = new Date();
        dcInvoice.setDate(date);

    }

    private void loadComboCustomer() {
        Customer Customerobj = new Customer();
        ArrayList<Customer> CustomerobjList = Customerobj.loadCustomer();
        if (CustomerobjList.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Sorry ! No Customers Found.");
        } else {
            Vector v = new Vector();
            Customer Customerss = new Customer();
            int count = 0;
            while (CustomerobjList.size() > count) {
                // hiddenValue hv= new hiddenValue();
                Customerss = CustomerobjList.get(count);

                // hv.setVisibleField(Categoryss.getCatName());
                // hv.setHiddenField(Categoryss.getCatID());
                v.add(Customerss.getC_name());

                count++;
            }
            ddlCustomer.setModel(new DefaultComboBoxModel(v));

        }
    }

    private void loadProductTable() {
        Stocks Productsobj = new Stocks();
        ArrayList<Stocks> ProductsList = Productsobj.loadStocks();
        if (ProductsList.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Sorry ! No Product Found.");
        } else {
            DefaultTableModel dtm = (DefaultTableModel) tblproductSelect.getModel();
            dtm.setRowCount(0);
            int count = 0;
            while (ProductsList.size() > count) {
                Vector v = new Vector();
                Stocks Productss = new Stocks();
                Productss = ProductsList.get(count);

                v.add(Productss.getPID());
                v.add(Productss.getBatch());
                v.add(Productss.getDescription());
                v.add(Productss.getSprice());

                dtm.addRow(v);
                count++;

            }
        }

    }

    private void loadSerchProductTable(String text) {
        Stocks Productsobj = new Stocks();
        ArrayList<Stocks> ProductsList = Productsobj.searchStocks(text);
        if (ProductsList.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Sorry ! No Product Found.");
        } else {
            DefaultTableModel dtm = (DefaultTableModel) tblproductSelect.getModel();
            dtm.setRowCount(0);
            int count = 0;
            while (ProductsList.size() > count) {
                Vector v = new Vector();
                Stocks Productss = new Stocks();
                Productss = ProductsList.get(count);

                v.add(Productss.getPID());
                v.add(Productss.getBatch());
                v.add(Productss.getDescription());
                v.add(Productss.getSprice());

                dtm.addRow(v);
                count++;

            }
        }

    }

    private float calNet(JTable tbl, int col) {
        float total = 0;
        DefaultTableModel dtm = (DefaultTableModel) tbl.getModel();
        for (int i = 0; tbl.getRowCount() > i; i++) {
            total += Float.parseFloat(dtm.getValueAt(i, col).toString());
        }
        return total;
    }

    private void setDiscTotal(float net, float rate) {
        float disc = (net / 100) * rate;
        float total = net - disc;
        txtDiscountValue.setText(disc + "");
        txtTotal.setText(total + "");
    }

    private boolean addInvoices(int id, String type, String pono, int creditPeriod, String date, String Customer, float Net, float Discount, float total, int stat) {
        boolean status;
        Invoices obj = new Invoices();
        obj.setInvoNo(id);
        obj.setType(type);
        obj.setPoNo(pono);
        obj.setCreditPreiod(creditPeriod);
        obj.setCustomer(Customer);
        obj.setDate(date);
        obj.setNet(Net);
        obj.setDiscount(Discount);
        obj.setTotal(total);
        obj.setStatus(stat);

        status = obj.addInvoices(obj);
        if (status) {
            status = addInvoicesregistryBulk(obj);
        }

        return status;
    }

    private boolean addInvoicesregistryBulk(Invoices obj) {
        ArrayList<InvoiceRegistry> list = new ArrayList<InvoiceRegistry>();
        DefaultTableModel dtm = (DefaultTableModel) tblInvoice.getModel();

        for (int raw_id = 0; tblInvoice.getRowCount() > raw_id; raw_id++) {
            InvoiceRegistry regObj = new InvoiceRegistry();
            regObj.setInvoNo(obj.getInvoNo());
            regObj.setBatch(dtm.getValueAt(raw_id, 2).toString());
            regObj.setPID(Integer.parseInt(dtm.getValueAt(raw_id, 1).toString()));
            regObj.setDescription(dtm.getValueAt(raw_id, 3).toString());
            regObj.setSPrice(Float.parseFloat(dtm.getValueAt(raw_id, 4).toString()));
            regObj.setQty(Integer.parseInt(dtm.getValueAt(raw_id, 5).toString()));
            regObj.setAmount(Float.parseFloat(dtm.getValueAt(raw_id, 6).toString()));

            list.add(regObj);
        }
        InvoiceRegistry PRobj = new InvoiceRegistry();
        boolean stat = PRobj.addInvoiceRegistryBulk(list);
        if (stat) {
            stat = updateStockQty(list);
        }
        return stat;
    }

    private void clearAll() {
        DefaultTableModel dtm = (DefaultTableModel) tblInvoice.getModel();
        dtm.setRowCount(0);
        loadComboCustomer();
        txtNet.setText("");
        txtDiscountValue.setText("");
        txtTotal.setText("");
        setID();
        
    }

    public boolean updateStockQty(ArrayList<InvoiceRegistry> list) {
        Stocks obj = new Stocks();
        boolean stat = false;
        for (int count = 0; list.size() > count; count++) {
            //this is Invoice so the type is 0
            InvoiceRegistry Invoobj = list.get(count);
            stat = obj.updateQty(Invoobj.getPID(), Invoobj.getBatch(), Invoobj.getQty(), 0);
        }
        return stat;
    }

    private void printReport() {
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String dt = df.format(dcInvoice.getDate());
        try {
            JRTableModelDataSource ds = new JRTableModelDataSource(tblInvoice.getModel());
            String rs = "src\\RPT\\Invoice.jrxml";
            Map<String, Object> param = new HashMap<String, Object>();
            param.put("InNo", txtInvoiceNo.getText());
            param.put("C_name", ddlCustomer.getSelectedItem().toString());
            param.put("pono", txtPOno.getText());
            param.put("In_date", dt);
            param.put("Net", txtNet.getText());
            param.put("Total", txtTotal.getText());
            param.put("DiscRate", txtDiscuntPresentage.getText());
            param.put("DiscAmount", txtDiscountValue.getText());

            JasperReport jr = JasperCompileManager.compileReport(rs);
            JasperPrint jp = JasperFillManager.fillReport(jr, param, ds);
            JasperViewer.viewReport(jp, false);

        } catch (JRException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
}
